version: 0.0
os: linux
files:
  - source: scripts/
    destination: /home/ec2-user/scripts/
hooks:
  ApplicationStop:
    - location: /home/ec2-user/scripts/application_stop.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /home/ec2-user/scripts/application_start.sh
      timeout: 300
      runas: root
