version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.12.2
    commands:
      - echo "Installing dependencies..."
      - npm install
      - npm install react-scripts@5.0.1
      - npm install react-router-dom
    
  pre_build:
    commands:
      - INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=mjy-dev-instance" --query "Reservations[0].Instances[0].InstanceId" --output text)
      - INSTANCE_PUBLIC_IP=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query "Reservations[0].Instances[0].PublicIpAddress" --output text)
      - REACT_APP_domain="$INSTANCE_PUBLIC_IP:8080"
      - export REACT_APP_domain

  build:
    commands:
      - echo "Building React project..."
      - npm run build

  post_build:
    commands:
      - echo "Updating files in the S3 bucket..."
      - aws s3 sync build/ s3://mjy-static-test-deploy --delete --exclude "images/*"
