version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.12.2
    commands:
      - echo "Installing dependencies..."
      - npm install
      - npm install react-scripts@5.0.1
      - npm install --save react-s3
    
  pre_build:
    commands:
      - secret=$(aws secretsmanager get-secret-value --secret-id /CodeBuild/mjy-key --query SecretString --output text)
      - Access_key_ID=$(echo "$secret" | jq -r '.Access_key_ID')
      - Secret_access_key=$(echo "$secret" | jq -r '.Secret_access_key')
      - export Access_key_ID
      - export Secret_access_key

  build:
    commands:
      - echo "Building React project..."
      - echo $Access_key_ID
      - echo $Secret_access_key
      - npm run build

  post_build:
    commands:
      - echo "Updating files in the S3 bucket..."
      - aws s3 sync build/ s3://mjy-static-deploy --delete
