version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.12.2
    commands:
      - echo "Installing dependencies..."
      - npm install
      - npm install react-scripts@5.0.1
      - npm install react-router-dom
    
  pre_build:
    commands:
      # - secret=$(aws secretsmanager get-secret-value --secret-id /CodeBuild/mjy-key --query SecretString --output text)
      # - REACT_APP_ID=$(echo "$secret" | jq -r '.Access_key_ID')
      # - REACT_APP_SECRET=$(echo "$secret" | jq -r '.Secret_access_key')
      - REACT_APP_domain="https://back.jaejae.store"
      # - export REACT_APP_ID
      # - export REACT_APP_SECRET
      - export REACT_APP_domain
      # - echo $REACT_APP_domain $REACT_APP_ID

  build:
    commands:
      - echo "Building React project..."
      - npm run build

  post_build:
    commands:
      - echo "Updating files in the S3 bucket..."
      - aws s3 sync build/ s3://mjy-static-deploy --delete --exclude "images/*"
