version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR....
      - aws --version
      - secret=$(aws secretsmanager get-secret-value --secret-id /CodeBuild/docker --query SecretString --output text)
      - docker_username=$(echo "$secret" | jq -r '.username')
      - docker_password=$(echo "$secret" | jq -r '.password')
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 992382777416.dkr.ecr.us-east-2.amazonaws.com
      - REPOSITORY_URI=992382777416.dkr.ecr.us-east-2.amazonaws.com/mjy-app

  build:
    commands:
      - echo Build started on `date`docker
      - echo building the Jar file
      - mvn clean package -DskipTests
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:app-deploy .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo pushing to repo
      - docker push $REPOSITORY_URI:app-deploy
      - echo Writing image definitions file...
      # Give your container name
      - DOCKER_CONTAINER_NAME=mjy-app
      - printf '[{"name":"%s","imageUri":"%s"}]' $DOCKER_CONTAINER_NAME $REPOSITORY_URI:app-deploy > imagedefinitions.json
      - echo $DOCKER_CONTAINER_NAME
      - echo printing imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
