version: 0.2

env:
  variables:
    REPOSITORY_URI: "lygerin14/test"
    IMAGE_TAG: "app-deploy"

phases:
  pre_build:
    commands:
      # - echo Logging in to Amazon ECR....
      # - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 992382777416.dkr.ecr.us-east-2.amazonaws.com
      # - REPOSITORY_URI=992382777416.dkr.ecr.us-east-2.amazonaws.com/mjy-app
      - echo Logging into docker
      - docker_secret=$(aws secretsmanager get-secret-value --secret-id /CodeBuild/docker --query SecretString --output text)
      - docker_username=$(echo "$docker_secret" | jq -r '.username')
      - docker_password=$(echo "$docker_secret" | jq -r '.password')
      - echo $docker_password | docker login -u $docker_username --password-stdin

  build:
    commands:
      - echo Build started on `date`
      - echo building the Jar file
      - mvn clean package -DskipTests
      - echo Building the Docker image...
      - docker build -t -e db_endpoint=DB_ENDPOINT $REPOSITORY_URI:$IMAGE_TAG .
      - echo pushing to repo
      - docker push $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - echo '{"imageTag": "app-deploy", "imageURI": lygerin14/test:app-deploy"}' > imageDetail.json

artifacts:
  files:
    - imageDetail.json
    - appspec.yml