version: 0.2

env:
  variables:
    REPOSITORY_URI: "lygerin14/test"
    IMAGE_TAG: "app-deploy"

phases:
  pre_build:
    commands:
      - echo Logging into docker
      - docker_secret=$(aws secretsmanager get-secret-value --secret-id /CodeBuild/docker --query SecretString --output text)
      - docker_username=$(echo "$docker_secret" | jq -r '.username')
      - docker_password=$(echo "$docker_secret" | jq -r '.password')
      - echo $docker_password | docker login -u $docker_username --password-stdin
      - aws s3 cp s3://mjy-bucket/key/mjy-key-pair.pem .
      - chmod 400 mjy-key-pair.pem
      - APP_INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=mjy-dev-app-instance" --query "Reservations[0].Instances[0].InstanceId" --output text)
      - APP_INSTANCE_PUBLIC_IP=$(aws ec2 describe-instances --instance-ids $APP_INSTANCE_ID --query "Reservations[0].Instances[0].PublicIpAddress" --output text)
      - ssh-keyscan -H $APP_INSTANCE_PUBLIC_IP >> ~/.ssh/known_hosts
      - DB_INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=mjy-dev-db-instance" --query "Reservations[0].Instances[0].InstanceId" --output text)
      - DB_ENDPOINT=$(aws ec2 describe-instances --instance-ids $DB_INSTANCE_ID --query "Reservations[0].Instances[0].PrivateIpAddress" --output text)
      - echo $DB_ENDPOINT

  build:
    commands:
      - echo Build started on `date`
      - echo building the Jar file
      - mvn clean package -DskipTests
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - echo pushing to repo
      - docker push $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - ssh -i mjy-key-pair.pem ec2-user@$APP_INSTANCE_PUBLIC_IP "sudo docker stop mjy-app || true"
      - ssh -i mjy-key-pair.pem ec2-user@$APP_INSTANCE_PUBLIC_IP "sudo docker rm mjy-app || true"
      - ssh -i mjy-key-pair.pem ec2-user@$APP_INSTANCE_PUBLIC_IP "echo $docker_password | sudo docker login -u $docker_username --password-stdin"
      - ssh -i mjy-key-pair.pem ec2-user@$APP_INSTANCE_PUBLIC_IP "sudo docker pull $REPOSITORY_URI:$IMAGE_TAG"
      - ssh -i mjy-key-pair.pem ec2-user@$APP_INSTANCE_PUBLIC_IP "sudo docker run -d -p 8080:8080 --name mjy-app -e db_endpoint=$DB_ENDPOINT $REPOSITORY_URI:$IMAGE_TAG"
      - >
        echo '{"ImageURI": "lygerin14/test:app-deploy"}' > imageDetail.json
      - ssh -i mjy-key-pair.pem ec2-user@$APP_INSTANCE_PUBLIC_IP "history"

artifacts:
  files:
    - imageDetail.json
