variable "aurora-cluster-identifier" {}
variable "db-subnet-group-name" {}
variable "private-subnet-name" {}
variable "db-subnets" {}
variable "db-sg-name" {}
variable "azs" {}
variable "rds-username" {}
variable "rds-pwd" {}
variable "rds-name" {}
variable "db-name" {}
variable "vpc-name" {}
variable "rds-instance-class" {}